version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  # db:
  #   image: mariadb
  #   expose:
  #     - 3306:3306
  #   environment:
  #     - MARIADB_ROOT_PASSWORD=root
  #     - MARIADB_DATABASE=srt
  #     - MARIADB_USER=srt
  #     - MARIADB_PASSWORD=srtpassword
  #   volumes:
  #     - ./data/db:/var/lib/mysql