version: '3'

services:
  app:
    build: dyaonly/srt-backend
    ports:
      - 3000:3000

  db:
    image: mariadb
    expose:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=srt
    volumes:
      - ./data/db:/var/lib/mysql